### ISSUE TITLE
Problem parsing login request

### ISSUE THREAD

**Issue by juspa1978** [AlbertHakvoort/Melcloud2Domoticz#8]
1/5/2021, 6:08:40 AM [melcloud2] There was a problem parsing login request: https://app.melcloud.com/Mitsubishi.Wifi.Client/Login/ClientLogin
1/5/2021, 6:08:40 AM [melcloud2] TypeError: Cannot read property 'ContextKey' of null
   
when trying to go page message page dont found
https://app.melcloud.com/Mitsubishi.Wifi.Client/Login/ClientLogin

**Comment by AlbertHakvoort** [comment]
Hi,

I just tried it on my own setup, and it's working fine. When going directly to the url https://app.melcloud.com/Mitsubishi.Wifi.Client/Login/ClientLogin I get a "Unexpected Error", but thats normal because we don't send any loging settings to the url..

Could you remove the .session file and restart the script manual?
